trigger:
  - main
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Node.js Kurulumu'

- script: |
    npm ci
  displayName: 'NPM Paketlerini Yükle'

- script: |
    npx playwright install --with-deps
  displayName: 'Playwright Tarayıcı Motorlarını Yükle'

- script: |
    npx playwright test
  displayName: 'Playwright Testlerini Çalıştır'

- task: PublishPipelineArtifact@1
  condition: always()
  inputs:
    targetPath: 'playwright-report'
    artifact: 'playwright-report'
    publishLocation: 'pipeline'
  displayName: 'HTML Raporunu Azure Pipelines-a Yükle'